### ISSUE TITLE
Add cloud support

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#10]

**Comment by thewtex** [comment]
1. https
2. S3
3. Google Cloud

**Comment by tbirdso** [comment]
Verified that both `https` and `s3` sources are addressed by way of `http` key/value store driver support in #37. Google Cloud may 
also be included or may require `gcs` driver support. https://google.github.io/tensorstore/kvstore/gcs/index.html

It would be good for someone with an active Google Cloud access to test that support.
