### ISSUE TITLE
Fix Linux Python package CI builds

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#13]
They will be needed for easy/automated PyPI package generation and uploading. The main issue is TensorBoard failing to build using `manylinux` toolchain, as detailed in https://github.com/google/tensorstore/issues/69.

**Comment by dzenanz** [comment]
I [tried](https://github.com/dzenanz/ITKIOOMEZarrNGFF/commit/1303cd9c4349f126f5c9ee1a06d6076c53f566aa) removing ASM setting from docker image. My effort seems completely ignored:
```log
[1023/2055] Building ASM object _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o
FAILED: _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o 
/opt/rh/gcc-toolset-11/root/bin//as --defsym XXH_NAMESPACE=ZSTD_ --defsym ZSTDLIB_HIDDEN="" --defsym ZSTDLIB_VISIBLE="" -I/work/ITK-source/ITK/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/Eigen3/src -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/KWSys/src -I/work/oneTBB-prefix/include -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-source/ITK/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/vcl -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/VNL/src/vxl/core -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/Core/Common -I/work/ITK-source/ITK/Modules/Core/Common/include -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/IO/ImageBase -I/work/ITK-source/ITK/Modules/IO/ImageBase/include -I/work/ITK-source/ITK/Modules/IO/HDF5/include -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src -I/work/ITK-cp37-cp37m-manylinux_2_28_x64/Modules/ThirdParty/ZLIB/src/itkzlib-ng -I/work/ITK-source/ITK/Modules/ThirdParty/ZLIB/src -I/work/include -I/work/_skbuild/linux-x86_64-3.7/cmake-build/include -I/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/zstd-build -I/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/zstd-build/lib -I/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/zstd-src -I/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/zstd-src/lib -O3 -DNDEBUG -fPIC -I/work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/zstd-src/lib/common --MD _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o.d -o _deps/zstd-build/CMakeFiles/Zstd_zstdlib.dir/lib/decompress/huf_decompress_amd64.S.o -c /work/_skbuild/linux-x86_64-3.7/cmake-build/_deps/zstd-src/lib/decompress/huf_decompress_amd64.S
/opt/rh/gcc-toolset-11/root/bin//as: invalid option -- 'N'
```
As I don't have permission to push docker images to dockcross, I pushed them to [my fork](https://hub.docker.com/r/dzenanz/manylinux_2_28-x64/tags). Maybe that is the problem? Or [packaging scripts](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/tree/removeASMfromToolchain) need a more thorough modification than [this](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/commit/5bad3bd9567e398b4582d70363d1ad57317ab3f6)? Or the [modification to docker files](https://github.com/dzenanz/dockcross/commits/removeASM) themselves is insufficient?

**Comment by thewtex** [comment]
Did the image build successfully locally? This should be tried first.

**Comment by dzenanz** [comment]
The docker image did build. I never succeeded at building wheels, either locally or in the CI.

**Comment by thewtex** [comment]
The wheels for this module should be built locally first.

**Comment by thewtex** [comment]
Please verify that the desired docker image is used.

**Comment by dzenanz** [comment]
[Removing ASM specifications](https://github.com/dzenanz/dockcross/commit/9bb0b2259d6f0afe0b38a2e352de710a5f79f639) gets me past the main issue (https://github.com/google/tensorstore/issues/69), but runs into a different error. I think it is the toolchain compatibility identified in https://github.com/InsightSoftwareConsortium/ITK/issues/3785#issuecomment-1338611048. Simply trying to [revert dockcross to gcc11](https://github.com/dzenanz/dockcross/commit/81ddc8347629a3a7ed57598fc9de1d16baf498fc) runs into:
```log
++ MANYLINUX_VERSION=_2_28
++ echo 'Building wheels for x64 using manylinux_2_28'
Building wheels for x64 using manylinux_2_28
+ sudo ldconfig
/opt/rh/gcc-toolset-12/root/usr/bin/sudo: line 41: /usr/bin/sudo: No such file or directory
Cleaning up artifacts from module build
```

**Comment by dzenanz** [comment]
@tbirdso do you know how to fix `/opt/rh/gcc-toolset-12/root/usr/bin/sudo: line 41: /usr/bin/sudo: No such file or directory`?

**Comment by thewtex** [comment]
As discussed at https://github.com/InsightSoftwareConsortium/ITK/issues/3785#issuecomment-1338751571
your dockcross patches should be added to a Git branch based on dockcross `459c9f0`.

**Comment by dzenanz** [comment]
That does it. The wheel builds locally with https://github.com/dzenanz/dockcross/commit/1aeaea06343b030cf0dd96f15e4a6398f71a0d95, `zarrCI` branch of ITKPythonPackage https://github.com/InsightSoftwareConsortium/ITKPythonPackage/commit/857e352dcf5e86bcd2e32a9826110352355b06ef. Current master, my fork's master and and https://github.com/dzenanz/ITKIOOMEZarrNGFF/tree/tensorstore should all build.

@thewtex I do not have permission to push `20230104-1aeaea0` tag to dockcross dockerhub. Could you do it, or give me permission?

**Comment by thewtex** [comment]
@dzenanz great news!

`dockcross/manylinux_2_28-x64:20230106-1aeaea0` have been pushed to DockerHub. Please create a PR with the branch to the dockcross repository.

**Comment by dzenanz** [comment]
I created a PR: https://github.com/dockcross/dockcross/pull/760. I tested with just removing `CMAKE_ASM_COMPILER`, and that was sufficient for building ITKIOOMEZarrNGFF package.
