### ISSUE TITLE
Document how to use via Python packages

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#17]
Current behavior:
```log
>>> image = itk.imread(r"C:\Dev\ITKIOOMEZarrNGFF\v0.4\cyx.ome.zarr")
WARNING: In C:\P\IPP\ITK-source\ITK\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 100
GDCMSeriesFileNames (000002D3727E1340): No Series were found

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Dzenan\miniconda3\envs\deep_learning\lib\site-packages\itk\support\extras.py", line 1251, in imread
    raise FileNotFoundError(f"no DICOMs in: {filename}.")
FileNotFoundError: no DICOMs in: C:\Dev\ITKIOOMEZarrNGFF\v0.4\cyx.ome.zarr.
```
should have been fixed by https://github.com/InsightSoftwareConsortium/ITK/commit/55bdee957fb1df23556bcf58f3ac049794e5ede8 which made it into [v5.3.0](https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.3.0).

**Comment by dzenanz** [comment]
@tbirdso can you double check this behavior? Do you have a suggested solution?

**Comment by tbirdso** [comment]
@dzenanz It looks like the fix in https://github.com/InsightSoftwareConsortium/ITK/commit/55bdee957fb1df23556bcf58f3ac049794e5ede8 requires that an ImageIO object is passed to `imread`, otherwise the directory will be interpreted as a DICOM directory.

What is the result of this line?

```py
image = itk.imread(r"C:\Dev\ITKIOOMEZarrNGFF\v0.4\cyx.ome.zarr", imageio=itk.OMEZarrNGFFImageIO.New())
```

**Comment by dzenanz** [comment]
That works. I guess that zarr IO is special in the sense that the "file name" is usually a directory. For [Scanco](https://github.com/KitwareMedical/ITKIOScanco) it works without specifying IO explicitly: `image = itk.imread(r"C:\Dev\ITK-vs19\Testing\Temporary\AIMIOTestImage2.isq")`.
