### ISSUE TITLE
CMake warning due to unescaped description

### ISSUE THREAD

**Issue by dzenanz** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#19]
a7fe05644fcce083226f8ac6e659726d614a4e08 changed readme format. Now I get a CMake warning when running locally, complaining about syntax from the `readme.md` document:

```log
CMake Warning (dev) at C:/Dev/ITK-git/CMake/ITKModuleMacros.cmake:98 (message):
  Unknown argument [

  ``

  In Python, we need to explicitly specify the IO, otherwise DICOM IO will be
  invoked because it is the built-in default for directories.  Example:
...
```
(It is hard to put the whole output here as it gets formatted by GitHub)

**Comment by dzenanz** [comment]
It would be trivial to write a short plain-text description in https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/blob/master/itk-module.cmake#L4 instead of reading it from file. @jhlegarreta @tbirdso Do we have a better solution?

**Comment by jhlegarreta** [comment]
Not sure if I have enough knowledge to answer this :pensive:, but
- Not sure why this has not been caught by the CI. IMO, CMake warnings should be signaled as failures. At least they should appear in the CDash dashboard.
- Other remotes are also using Markdown for their `README`s (maybe a minority), so the above may apply to them as well, e.g.
https://github.com/InsightSoftwareConsortium/ITKElastix/blob/main/itk-module.cmake#L4
https://github.com/InsightSoftwareConsortium/ITKFPFH/blob/master/itk-module.cmake#L4
https://github.com/InsightSoftwareConsortium/ITKThinShellDemons/blob/main/itk-module.cmake#L4

[ITKElastix](https://github.com/InsightSoftwareConsortium/ITKElastix) does have a code block, but they do not apply the language highlighting and just apply some indentation. However, [ITKFPFH](https://github.com/InsightSoftwareConsortium/ITKFPFH) does apply language highlighting:
https://github.com/InsightSoftwareConsortium/ITKFPFH/blob/master/README.md?plain=1#L17
https://github.com/InsightSoftwareConsortium/ITKFPFH/blob/master/README.md?plain=1#L37

- Looks like the ITK CMake macro expects some specific argument and none is matching https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKModuleMacros.cmake#L98. Not sure what `_doing` should be set to https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKModuleMacros.cmake#L55

Maybe @bradking is able to provide insight into this.

**Comment by dzenanz** [comment]
We should hit [DESCRIPTION](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3.0/CMake/ITKModuleMacros.cmake#L91). I gave up on trying to get to the bottom of this, and created #20.
