### ISSUE TITLE
Rename repository / module to ITKIOZarrNGFF

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#2]
@joshmoore do you agree that this is the best name, if we are supporting OME-Zarr / NGFF? Or `ITKIOOMEZarrNGFF`? Or `ITKIONGFF`, if we also support `N5` in this module?

**Comment by joshmoore** [comment]
Interesting (and philosophical) question! My best answer is "it depends". I'll write out my interpretation of several and see if that helps:

"The library ___ supports reading and writing ____":

* ITKIOZarr: "any Zarr files, independent of image specification"
* ITKIONGFF: "any next generation (i.e. cloud-optimized) formats"
* ITKIOZarrNGFF : "next-generation files but specifically Zarr, i.e. not necessarily image related" 
* ITKIOOMEZarrNGFF : "next-generation files but specifically OME-Zarr, i.e. image related"
* ITKIOOMEZarr: "OME-Zarr, i.e. the current image format"
* ITKIOOMENGFF: "next-generation image files whatever the backend"


Maybe a question: what is the complementary library used for OME-TIFF IO called?

**Comment by thewtex** [comment]
> Maybe a question: what is the complementary library used for OME-TIFF IO called?

We have `ITKIOTIFF`, but it is not specific to OME-TIFF. However, since these are image and spatial datasets based on zarr, I think we want to be more specific than `Zarr` in some way.

**Comment by dzenanz** [comment]
Repository renamed, now onto renaming files.
