### ISSUE TITLE
Add a parameter to select scale for multiscale support

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#22]

**Comment by tbirdso** [comment]
It looks like this was addressed in https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/commit/2563ad5f9234d7bf3e164be0f09cacd6d3de895a#diff-4a682cb0083c8b197c656772c74164a4e362b7d3e5be4c31f0c7324d34a8d049R106 with `SetDatasetIndex`. @thewtex do you agree that this issue could be closed?

**Comment by dzenanz** [comment]
Perhaps even rename it into something more intuitive, like `ScaleLevel` or `ResolutionLevel`.
