### ISSUE TITLE
BUG: Zip file output sometimes corrupted on Linux

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#36]
## Overview

Tests for reading from `.zip` file store sometimes fail. Exact cause is unclear at the moment.

First CI run (failed)
https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5716549674/job/15488329023?pr=35

Second CI run, no changes (passing):
https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5716549674/job/15490659684?pr=35

## Workaround

Re-running CI seems to work for now.

**Comment by tbirdso** [comment]
This is currently blocking the `v0.1.3` PyPI release: https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5739761493

**Comment by tbirdso** [comment]
Following investigation in https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/pull/44, it was observed that the `memory.zip` output of the `inMemory_zip` test is sometimes a corrupted archive. The exact cause for this is not clear. Behavior is observed regularly in CI and infrequently in local testing on Linux platforms.

The Tensorstore `zip` driver is maintained in the https://github.com/InsightSoftwareConsortium/tensorstore fork and is not maintained by Google. We will need to track this ourselves.

Following offline discussion, we will disable the failing test for now to prevent blocking PyPI releases and continue investigation in parallel with subsequent work.

**Comment by dzenanz** [comment]
After all the contents are added to in-memory zip file, the buffer size is 47447. After [`closeZip()`](https://github.com/InsightSoftwareConsortium/tensorstore/blob/afb30a4bcc4a3d93053509efb72edbfcd518e726/tensorstore/kvstore/zip/zip_key_value_store.cc#L148-L175) is called, the buffer size increases to the correct value of 47685. This leads me to suspect that [destructor](https://github.com/InsightSoftwareConsortium/tensorstore/blob/afb30a4bcc4a3d93053509efb72edbfcd518e726/tensorstore/kvstore/zip/zip_key_value_store.cc#L143-L146) is not invoked sometimes.

I will now try to fix this.

I originally wrote this in the wrong issue's discussion: https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/issues/48#issuecomment-1699529683

**Comment by dzenanz** [comment]
With rebasing, I ran into a snag: https://github.com/google/tensorstore/issues/110.

**Comment by dzenanz** [comment]
With building cleared up, the rebase does not help with crashes. We should still use the newer version of tensorstore, so I created this PR:
https://github.com/InsightSoftwareConsortium/tensorstore/pull/1
Please just review, do not click merge - this branch should become the new master.

**Comment by dzenanz** [comment]
#54 fixes the problem via a workaround. I still think that the original problem was caused by the [~ZipEncapsulator() destructor](https://github.com/InsightSoftwareConsortium/tensorstore/blob/afb30a4bcc4a3d93053509efb72edbfcd518e726/tensorstore/kvstore/zip/zip_key_value_store.cc#L143-L146) not always being called. But digging through tensorstore internals seemed daunting.
