### ISSUE TITLE
Investigate rebase on kvikio

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#4]
Investigate using kvikio for operations:

https://github.com/rapidsai/kvikio

Advantages:

- Good CMake support
- Header-only
- Apache 2.0 license
- C++17
- CPU support
- Uses internal parallel IO with thread pool with nice future interface
- Optional CUDA GPU support (requires CUDA-Toolkit)

**Comment by dzenanz** [comment]
Currently, GPU support is not optional. https://github.com/rapidsai/kvikio/pull/82 aims to integrate file IO which doesn't go through GPU. They have an example of using `kvikio` via CMake in a [PR](https://github.com/rapidsai/kvikio/pull/29/commits/b0811625feadda6ec6b0edbac298761f14deb38f). I am not sure that `kvikio` even has its own Zarr functionality, it [imports `zarr`](https://github.com/rapidsai/kvikio/blob/branch-22.08/python/benchmarks/single-node-io.py#L196-L229). I asked this [question about it](https://github.com/rapidsai/kvikio/issues/93).

**Comment by dzenanz** [comment]
This file looks like the only Zarr-specific implementation within `kvikio`: https://github.com/rapidsai/kvikio/blob/29c52f76035002d91f301895250c0ff14f18f50a/python/kvikio/zarr.py.
