### ISSUE TITLE
How to use ITKIOOMEZarrNGFF in C++?

### ISSUE THREAD

**Issue by N-Dekker** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#51]
Can you please elaborate a little bit more on how to use ITKIOOMEZarrNGFF in C++? I see, https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/blob/fe5bc3caecfe774e64acabfd75e9d74e22eacfb5/README.md says:

> Usage from C++ should not require any special action. In special situations, you might need to invoke:
```C++
itk::OMEZarrNGFFImageIOFactory::RegisterOneFactory();
```

Looks fine, but then, what steps are there to take to get it compiled? Is the idea for the client application to use something like `ExternalProject_Add(ITKIOOMEZarrNGFF ...)` in their CMakeLists.txt?

Is the intention to (eventually?) allow ITKIOOMEZarrNGFF to be selected as an optional module when CMake-configuring ITK?

**Comment by dzenanz** [comment]
> Is the intention to (eventually?) allow ITKIOOMEZarrNGFF to be selected as an optional module when CMake-configuring ITK?

Yes. But meanwhile, read on.

Depending on the build system, `ExternalProject_Add` is a possibility. Probably the easiest is to build ITK, then build ITKIOOMEZarrNGFF pointing to the ITK build directory, and then use that ITK build directory from then on.
