### ISSUE TITLE
Dependency simplification

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKIOOMEZarrNGFF#9]
Examples:

JSON:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/a67d9f07a47ed4e99406f3f91d856a8c5610e9a8/CMakeLists.txt#L34-L55

or

https://github.com/InsightSoftwareConsortium/itk-wasm/pull/670/files#diff-d29da74b9967e6709f76cd76b034f8178884f7787e288556b12951c911edf52bR13-R19

Blosc:

FetchContent + 
https://github.com/Kitware/itk-vtk-viewer/blob/7c88e1e055dc7c793561c4cdb106f9815c05a799/src/Compression/blosc-zarr/CMakeLists.txt#L4-L15

Zip:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/990082b1b0ebcbbe4467bb0222f64661b539dccb/CMakeLists.txt#L101-L147

**Comment by dzenanz** [comment]
Tensorstore [recently added](https://github.com/google/tensorstore/commit/3ab7edb8699aa90fe533ce0dcfe748a3aef77518) CMake support. It might be worthwhile to check it out again?

**Comment by dzenanz** [comment]
This issue is out of date now, and should be re-assessed.
